FROM ubuntu:22.04

RUN apt update
RUN apt --yes install sudo
# Set preferences for Microsoft .NET packages installation.
RUN cd /etc/apt/preferences.d && \
    touch 99microsoft-dotnet.pref && \
    echo 'Package: *' >> 99microsoft-dotnet.pref && \
    echo 'Pin: origin "packages.microsoft.com"' >> 99microsoft-dotnet.pref && \
    echo 'Pin-Priority: 1001' >> 99microsoft-dotnet.pref
# Update packages
RUN apt update
# Install .NET SDK 6.0
RUN apt --yes install dotnet-sdk-8.0
# Add .NET tools directory to PATH
RUN echo 'export PATH="$PATH:$HOME/.dotnet/tools"' >> /root/.bashrc
# Restarting shell for envariment variable changes
RUN exec $SHELL

RUN dotnet tool install -g firely.terminal
RUN apt --yes install nodejs
RUN apt --yes install default-jre
RUN apt --yes install npm
RUN apt --yes install maven
RUN apt --yes install httpie
RUN apt --yes install ruby-full build-essential zlib1g-dev
RUN apt --yes install curl
RUN apt --yes install apache2
RUN gem install jekyll bundler
RUN npm install -g --silent fsh-sushi@3.6.1
RUN npm install -g --silent fhirpath@3.10.1
RUN apt --yes install dos2unix
RUN apt --yes install graphviz

COPY exemplo.sh .
RUN dos2unix ./exemplo.sh
EXPOSE 80
CMD ["apache2ctl", "-D","FOREGROUND"]
