FROM ubuntu
RUN apt update
RUN apt --yes install nodejs
RUN apt --yes install default-jre
RUN apt --yes install npm
RUN apt --yes install maven
RUN apt --yes install httpie
RUN apt --yes install ruby-full build-essential zlib1g-dev
RUN apt --yes install curl
RUN apt --yes install apache2
RUN gem install jekyll bundler
RUN npm install -g --silent fsh-sushi@3.6.1
RUN npm install -g --silent fhirpath@3.10.1
RUN apt --yes install apache2
RUN apt --yes install dos2unix
COPY exemplo.sh .
RUN dos2unix ./exemplo.sh
EXPOSE 80
CMD ["apache2ctl", "-D","FOREGROUND"]